<a href="https://colab.research.google.com/github/jomariy241/daily-task/blob/main/daily_task_05_07_20246.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def lar(a,b,c):
  if a>b and a>c:
    lar=a
  elif b>a and b>c:
    lar=b
  elif c>a and c>b:
    lar=c
  return(lar)
user1=int(input("enter a number"))
user2=int(input("enter anumber"))
user3=int(input("enter a number"))
ans=lar(user1,user2,user3)
print(ans)

enter a number5
enter anumber6
enter a number3
6


In [ ]:
def area(r):
  ac=3.14*r*r
  return(ac)
a=int(input("enter radius"))
r=area(a)
print(r)

enter radius5
78.5


In [21]:
n=int(input("input a no."))
if n>1:
  for i in range(2,n):
     if(n%i==0):
      print(n,"is not prime")
      break
  else:
    print(n,"is prime")
else:
  print(n,"is prime")



input a no.6
6 is not prime


In [23]:
def palin(str):
 pl=str[::-1]
 if str==pl:
  return(True)
 else:
  return(False)
s=input("enter a string ")
palin(s)




enter a string malayalam


True

In [28]:
def sum(n):
  s=0
  for i in n:
    s+=i
  return(s)
list=[2,4,6,8]
a=sum(list)
print(a)



20


In [33]:
def avg(n):
  a=0
  for i in n:
    a=a+i
  return(a)
list=[3,6,34]
a=avg(list)
print(a)


43


In [39]:
def kth(arr,n):
  arr=sorted(arr,reverse=True)
  return arr[n-1]
list1=[4,6,8,5,5,7,9,10,9,8]
k=1
a=kth(list1,k)
print(a)


10


In [43]:
def sum(n):
	if n==0:
		return 0
	return(n%10+sum(int(n/10)))
r=60
ans=sum(r)
print(ans)

6


In [54]:
def power(p,n):
    ans=p
    for i in range(p-1):
        ans=ans*n
    return (ans)
a = 2
b = 5
print(power(a, b))



10


In [65]:
def hcf(num1, num2):
    if num2 == 0:
        return num1
    else:
        return hcf(num2, num1 % num2)
num1 = 78
num2 = 32
print(hcf(num1, num2))

2


In [83]:
import numpy as np
arr= np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a=np.arange(1,10)
b=a.reshape(3,3)
b



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
i=np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
r=np.random.randn(10)
m=np.mean(r)
sd=np.std(r)
print(m,sd)

-0.21619299030915284 0.759743456719031


In [95]:
r=np.arange(10,21)
e=r[:5]
e

array([10, 11, 12, 13, 14])

In [97]:
v = np.arange(0,16)
e=v.reshape(4,4)
print(e[1,:])

[4 5 6 7]


In [103]:
a1=np.arange(1,6)
a2=np.arange(6,11)
b=np.vstack((a1,a2))
a=a1+a2
a




array([ 7,  9, 11, 13, 15])

In [105]:
b= np.random.rand(10)
b[b< 0.5] = 0
b


array([0.        , 0.92808747, 0.        , 0.        , 0.57143919,
       0.65143261, 0.        , 0.        , 0.        , 0.69780083])